### ISSUE TITLE
ERROR: Not enough fields.

### ISSUE THREAD

**Issue by arbarhm** [ComputationalGenomics/HaplotypeAssembler#1]
Hi,
I am trying to run haplotype_assembler with the example data and command provided, however, I  am encountering the following error without any further details.
./haplotype_assembler --ploidy 4 --input-bam input_read_mapping.bam --input-vcf input_genotypes_ploidy4.vcf --output-vcf phased.vcf --dosages exact
ERROR: Not enough fields. 
Also, may I request to provide example commands you used to generate the input vcf file from the bam file.

Regards.

**Comment by haiminen** [comment]
Hi,
Thank you for trying out the assembler, indeed there was a formatting issue with the example input file.
Please try with the new example.sam and example.vcf files.
Best Wishes

**Comment by arbarhm** [comment]
Thanks. Working fine now.
